In [2]:
import numpy as np
%matplotlib inline

In [3]:
#Load the data
before_opt = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
after_opt = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 33])

In [5]:
before_opt.shape[0]

12L

In [7]:
shoe_sales = np.array([np.append(np.zeros(before_opt.shape[0]), np.ones(after_opt.shape[0])),
np.append(before_opt, after_opt)], dtype=int)
print shoe_sales

[[ 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1]
 [23 21 19 24 35 17 18 24 33 27 21 23 31 28 19 24 32 27 16 41 23 32 29 33]]


In [8]:
print shoe_sales.shape

(2L, 24L)


In [9]:
shoe_sales = shoe_sales.T
print "Shape :", shoe_sales.shape
print "Data:", "\n", shoe_sales

Shape : (24L, 2L)
Data: 
[[ 0 23]
 [ 0 21]
 [ 0 19]
 [ 0 24]
 [ 0 35]
 [ 0 17]
 [ 0 18]
 [ 0 24]
 [ 0 33]
 [ 0 27]
 [ 0 21]
 [ 0 23]
 [ 1 31]
 [ 1 28]
 [ 1 19]
 [ 1 24]
 [ 1 32]
 [ 1 27]
 [ 1 16]
 [ 1 41]
 [ 1 23]
 [ 1 32]
 [ 1 29]
 [ 1 33]]


In [12]:
print shoe_sales[:5,:]

[[ 0 23]
 [ 0 21]
 [ 0 19]
 [ 0 24]
 [ 0 35]]


In [15]:
experiment_label = np.random.randint(0,2,shoe_sales.shape[0])
experiment_data = np.array([experiment_label, shoe_sales[:,1]])
experiment_data = experiment_data.T

print experiment_data[:,0]==1

[False False False False  True  True False  True False  True  True False
  True  True  True False  True  True False  True False False False False]


In [16]:
experiment_data[experiment_data[:,0]==1]

array([[ 1, 35],
       [ 1, 17],
       [ 1, 24],
       [ 1, 27],
       [ 1, 21],
       [ 1, 31],
       [ 1, 28],
       [ 1, 19],
       [ 1, 32],
       [ 1, 27],
       [ 1, 41]])

In [19]:
print (np.empty([10,1]))

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
