In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [5]:
b = np.array([(5,6,7), (1,2,3)])
b

array([[5, 6, 7],
       [1, 2, 3]])

In [7]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [9]:
c = a - b
c

array([20, 29, 38, 47])

In [10]:
b**2

array([0, 1, 4, 9])

In [11]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

A*B

array([[2, 0],
       [0, 4]])

In [12]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [13]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [14]:
def f(x, y):
    return 10*x*y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[  0,   0,   0,   0],
       [  0,  10,  20,  30],
       [  0,  20,  40,  60],
       [  0,  30,  60,  90],
       [  0,  40,  80, 120]])

In [15]:
b[2,3]

60

In [16]:
b[0:5, 1]

array([ 0, 10, 20, 30, 40])

In [17]:
b[0:5, 1:2]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [18]:
b[0:5, 1:3]

array([[ 0,  0],
       [10, 20],
       [20, 40],
       [30, 60],
       [40, 80]])

In [19]:
for row in b:
    print row

[0 0 0 0]
[ 0 10 20 30]
[ 0 20 40 60]
[ 0 30 60 90]
[  0  40  80 120]


In [20]:
a = np.floor(10 * np.random.random((3,4)))
a

array([[ 7.,  7.,  0.,  3.],
       [ 2.,  3.,  0.,  7.],
       [ 9.,  4.,  1.,  7.]])

In [22]:
a.shape

(3, 4)

In [23]:
a.ravel()

array([ 7.,  7.,  0.,  3.,  2.,  3.,  0.,  7.,  9.,  4.,  1.,  7.])

In [24]:
a.shape = (6,2)
a.T

array([[ 7.,  0.,  2.,  0.,  9.,  1.],
       [ 7.,  3.,  3.,  7.,  4.,  7.]])

In [25]:
a

array([[ 7.,  7.],
       [ 0.,  3.],
       [ 2.,  3.],
       [ 0.,  7.],
       [ 9.,  4.],
       [ 1.,  7.]])

In [27]:
a.resize(2,6)
a

array([[ 7.,  7.,  0.,  3.,  2.,  3.],
       [ 0.,  7.,  9.,  4.,  1.,  7.]])

In [28]:
a.reshape(3, -1)
a

array([[ 7.,  7.,  0.,  3.,  2.,  3.],
       [ 0.,  7.,  9.,  4.,  1.,  7.]])

In [29]:
a.reshape(3, -1)

array([[ 7.,  7.,  0.,  3.],
       [ 2.,  3.,  0.,  7.],
       [ 9.,  4.,  1.,  7.]])

In [30]:
np.random.rand(2,3)

array([[ 0.44135737,  0.41465412,  0.05058096],
       [ 0.74957833,  0.49709129,  0.02574732]])

In [31]:
np.random.randint(5,10) #to generate a single number in [5, 10)

8

In [32]:
np.random.poisson(6.0) # to draw from the discrete Poisson distribution with 6.0

7

In [33]:
np.random.normal(size = 5) #to draw multiple values

array([-0.47136016, -1.16562746, -1.45225089,  0.94685182, -0.19970489])